# Generated by Django 4.0.5 on 2022-07-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='my_data')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
