# Generated by Django 4.0.5 on 2022-07-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_type_remove_shopgallery_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopgallery',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
